function createfigure(ymatrix1, X1, Y1)
%CREATEFIGURE(YMATRIX1, X1, Y1)
%  YMATRIX1:  stem matrix data
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 17-Oct-2017 14:31:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to stem
stem1 = stem(ymatrix1,'MarkerSize',5);
set(stem1(1),'DisplayName','Sine coeffs','Color',[0 0 1]);
set(stem1(2),'DisplayName','l_2 recovery','MarkerFaceColor',[0.5 0.5 0.9],...
    'MarkerEdgeColor',[1 0 0],...
    'Marker','x',...
    'Color',[1 0 0]);

% Create stem
stem(X1,Y1,'DisplayName','Spike coeffs','MarkerFaceColor',[0 0 1],...
    'MarkerSize',5,...
    'Color',[1 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 128]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.8 3]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',8);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.0928889050255329 0.667454848279272 0.295348832166443 0.248892919680761]);

